# Documentation: https://roots.io/trellis/docs/mail/
mail_smtp_server: inbound-smtp.us-west-2.amazonaws.com
mail_admin: admin@snugcode.com
mail_hostname: snugcode.com
mail_user: smtp_user
mail_password: "{{ vault_mail_password }}" # Define this variable in group_vars/all/vault.yml
